# This is a basic workflow to help you get started with Actions
name: Community Notification
on:
  push:
    branches: 
      - master
jobs:
  send-matrix-message:
    runs-on: ubuntu-latest
    steps:
      - name: matrix-message
        # You may pin to the exact commit or the version.
        # uses: s3krit/Matrix-Message@70ad3fb812ee0e45ff8999d6af11cafad11a6ecf
        uses: s3krit/Matrix-Message@v0.0.3
        with:
          # Matrix server hostname
          server: "matrix.private-cloud.network"
          # Matrix room ID, specified in channels advanced settings
          room_id: "${{ secrets.MATRIX_INFO_ROOM_ID }}"
          # Access token required to send to matrix server
          access_token: "${{ secrets.MATRIX_GITHUB_BOT_ACCESS_TOKEN }}"
          # Message to send in plaintext format
          message: "The challenges repo has been updated! It's pulling time, everyone!"
  
